embench/embench-meetings

- meetings/2020-11-16-agenda.md
Files changed:
* meetings/2020-11-16-agenda.md: Created.
> Agenda for meeting of 16 Nov 2020

- meetings/2020-11-16-agenda.md
Files changed:
* meetings/2020-11-16-agenda.md: Links to agenda items added, some
updates to status items, report from Sheena Goel dropped.
> Updated agenda for meeting on 16 Nov 2020

- meetings/2020-11-16-minutes.md
Files changed:
* meetings/2020-11-16-minutes.md: Created.
> Minutes from 16 November 2020 meeting.

- meetings/2020-12-14-agenda.md
Files changed:
* meetings/2020-12-14-agenda.md: Created.
> Agenda for the 12 Dec 2020 meeting.

- meetings/2021-01-11-minutes.md
Files changed:
* meetings/2021-01-11-minutes.md: Created.
> Minutes of meeting of 11 January 2021

- meetings/2021/2021-02-15-agenda.md
Files changed:
* meetings/2021/2021-02-15-agenda.md: Renamed from
2021-02-14-agenda.md.
> Correct filename of agenda for meeting on 15 February 2021.

- meetings/2021/2021-02-15-minutes.md
Files changed:
* meetings/2021/2021-02-15-minutes.md: Created.
> Minutes for Embench meeting 15 Feb 2021

- meetings/2021/2021-03-15-agenda.md
Files changed:
* meetings/2021/2021-03-15-agenda.md: Created.
> Agenda for meeting of 15 March 2021.

- meetings/2021/2021-04-19-agenda.md
- meetings/supplementary-materials/speed-and-rate-metric.adoc
Files changed:
* meetings/2021/2021-04-19-agenda.md: Add one more issue and
agenda item on speed/rate metric proposal.
* meetings/supplementary-materials/speed-and-rate-metric.adoc: Created.
> Updated agenda for 19 April 2021.

- meetings/2021/2021-04-19-agenda.md
Files changed:
* meetings/2021/2021-04-19-agenda.md: Add issue 135.
> Updated agenda (again) for 19 April 2021.

- meetings/2021/2021-05-17-agenda.md
Files changed:
* meetings/2021/2021-05-17-agenda.md: Created.
> Agenda for meeting on 17 May 2021.

- meetings/2021/2021-05-17-minutes.md
Files changed:
* meetings/2021/2021-05-17-minutes.md: Created.
> Minutes from meeting of 17 May 2021.

- meetings/2021/2021-07-19-agenda.md
Files changed:
* meetings/2021/2021-07-19-agenda.md: Created.
> Agenda for Embench meeting 19 July 2021.

- meetings/2021/2021-07-19-minutes.md
Files changed:
* meetings/2021/2021-07-19-minutes.md: Created.
> Minutes from meeting of 19 July 2021.

- meetings/2021/2021-08-16-agenda.md
Files changed:
* meetings/2021/2021-08-16-agenda.md: Created.
> Agenda for 16 August.

- meetings/2021/2021-08-16-minutes.md
Files changed:
* meetings/2021/2021-08-16-minutes.md: Created.
> Minutes of meeting of 16 August 2021.

- meetings/2021/2021-09-20-agenda.md
Files changed:
* meetings/2021/2021-09-20-agenda.md: Created.
> Agenda for meeting on 20 September 2021.

- meetings/2021/2021-09-20-minutes.md
Files changed:
* meetings/2021/2021-09-20-minutes.md: Created.
Signed-off-by: Paolo Savini <paolo.savini@gmail.com>
> Minutes of meeting of 20 September 2021. (#26)

- meetings/2021/2021-10-18-agenda.md
Files changed:
* meetings/2021/2021-10-18-agenda.md: Created.
> Agenda for meeting 18 October 2021

- meetings/2021/2021-11-15-agenda.md
Files changed:
* meetings/2021/2021-11-15-agenda.md: Created.
> Agenda for meeting on 15 Nov 2021.

- meetings/2021/2021-12-13-agenda.md
Files changed:
* meetings/2021/2021-12-13-agenda.md: Created.
> Agenda for meeting of 13 December 2021.

- meetings/2021/2021-12-13-minutes.md
Files changed:
* meetings/2021/2021-12-13-minutes.md: Created.
> Minutes of Embench meeting of 13 Dec 2021.

- meetings/2022/2022-02-21-agenda.md
Files changed:
* meetings/2022/2022-02-21-agenda.md: Created.
> Draft agenda for meeting of 21 Feb 2022.

- meetings/2022/2022-02-21-minutes.md
Files changed:
* meetings/2022/2022-02-21-minutes.md: Created.
> Minuted of Embench meeting of 21 February 2022.

- meetings/2022/2022-03-21-agenda.md
Files changed:
* meetings/2022/2022-03-21-agenda.md: Created.
> Agenda for Embench meeting of 21 March 2022.

- meetings/2022/2022-03-21-minutes.md
Files changed:
* meetings/2022/2022-03-21-minutes.md: Created.
> Minutes of meeting on 21 March 2022.

- meetings/2022/2022-04-25-agenda.md
Files changed:
* meetings/2022/2022-04-25-agenda.md: Created.
> Draft agenda for meeting of 25 April 2022.

- meetings/2022/2022-04-25-minutes.md
Files changed:
* meetings/2022/2022-04-25-minutes.md: Created.
> Minutes of Embench meeting of 25 April 2022.

- meetings/2022/2022-05-16-agenda.md
Files changed:
* meetings/2022/2022-05-16-agenda.md: Created.
> Agenda for Embench meeting of 16 May 2022.

- meetings/2022/2022-05-16-minutes.md
Files changed:
* meetings/2022/2022-05-16-minutes.md: Created.
> Minutes from meeting of 16 May 2022.

- meetings/2022/2022-06-20-agenda.md
Files changed:
* meetings/2022/2022-06-20-agenda.md: Created.
> Agenda for meeting of 20 June 2022.

- meetings/2022/2022-06-20-minutes.md
Files changed:
* 2022/2022-06-20-minutes.md: Created.
> Minutes for 20 June 2022 meeting.

- meetings/2022/2022-07-18-agenda.md
Files changed:
* 2022/2022-07-18-agenda.md: Created.
> Agenda for 18 July 2022 meeting.

- meetings/2022/2022-07-18-minutes.md
Files changed:
* 2022/2022-07-18-minutes.md: Created.
> Minutes for meeting of 18 July 2022.

- meetings/2022/2022-08-15-agenda.md
Files changed:
* meetings/2022/2022-08-15-agenda.md: Created.
> Draft agenda for Embench meeting 15 August 2022.

- meetings/2022/2022-08-15-minutes.md
* meetings/2022/2022-08-15-minutes.md: Created.
> Minutes of meeting of 5 August.

- meetings/2022/2022-09-19-agenda.md
* meetings/2022/2022-09-19-agenda.md: Created.
> Draft agenda for 19 September 2022.

- meetings/2022/2022-09-19-minutes.md
* meetings/2022/2022-09-19-minutes.md: Created.
> Minutes of meeting of 19 September.

- meetings/2022/2022-10-17-agenda.md
* meetings/2022/2022-10-17-agenda.md: Created.
> Draft agenda for meeting of 17 Oct 2022.

- meetings/2022/2022-11-21-agenda.md
* meetings/2022/2022-11-22-agenda.md: Created.
> Agenda for Embench call on 21 November 2022.

- meetings/2022/2022-11-21-minutes.md
* meetings/2022/2022-11-22-minutes.md: Created.
Signed-off-by: Paolo Savini <paolo.savini@gmail.com>
> Minutes for Embench call on 21 November 2022.

- meetings/2022/2022-12-11-agenda.md
* meetings/2022/2022-12-11-agenda.md: Created.
> Draft agenda for Embench meeting of 11 December 2022.

- meetings/2022/2022-12-12-agenda.md
- meetings/2022/2022-12-12-minutes.md
* meetings/2022/2022-12-12-agenda.md: Renamed. Fixed date inside.
* meetings/2022/2022-12-12-minutes.md: Created.
Signed-off-by: Paolo Savini <il.paolo.savini@gmail.com>
> Minutes and date fix in agenda for Embench call on 12 December 2022.
